"""
Evaluators module for LlamaBench.

This module provides evaluation metrics for benchmark tasks.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


class Evaluator(ABC):
    """Abstract base class for all evaluators."""

    @abstractmethod
    def evaluate(self, model_output: str, reference_output: str) -> float:
        """
        Evaluate a model's output against a reference output.

        Args:
            model_output: The output generated by the model
            reference_output: The reference output to compare against

        Returns:
            A score between 0.0 and 1.0 indicating how well the model output matches
            the reference output
        """
        pass


class ExactMatchEvaluator(Evaluator):
    """Evaluator that checks for exact string match (after normalization)."""

    def __init__(self, case_sensitive: bool = False, strip_whitespace: bool = True):
        """
        Initialize an exact match evaluator.

        Args:
            case_sensitive: Whether to perform case-sensitive matching
            strip_whitespace: Whether to strip leading/trailing whitespace
        """
        self.case_sensitive = case_sensitive
        self.strip_whitespace = strip_whitespace

    def evaluate(self, model_output: str, reference_output: str) -> float:
        """
        Evaluate if the model output exactly matches the reference output.

        Args:
            model_output: The output generated by the model
            reference_output: The reference output to compare against

        Returns:
            1.0 if there's an exact match, 0.0 otherwise
        """
        if self.strip_whitespace:
            model_output = model_output.strip()
            reference_output = reference_output.strip()

        if not self.case_sensitive:
            model_output = model_output.lower()
            reference_output = reference_output.lower()

        return 1.0 if model_output == reference_output else 0.0


__all__ = ["Evaluator", "ExactMatchEvaluator"]
